name: core-traefik

services:
  traefik:
    image: traefik:v3.6
    container_name: core_traefik_edge
    restart: unless-stopped
    user: "0:0"
    command:
      - --certificatesresolvers.cloudflare.acme.email=${ACME_TRAEFIK_EMAIL}
    environment:
      ACME_TRAEFIK_EMAIL: ${ACME_TRAEFIK_EMAIL}
      CF_DNS_API_TOKEN: ${CF_TRAEFIK_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config:/etc/traefik/config:ro
      - /condolab/docker/traefik/certs/acme.json:/etc/traefik/acme/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker_ipvlan

networks:
  docker_ipvlan:
    name: ipvlan
    external: true
