---
docker_dpkg_architecture_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf
docker_ipvlan_enabled: false
docker_ipvlan_name: docker_ipvlan
docker_ipvlan_mode: l3
docker_ipvlan_parent: ""
docker_ipvlan_subnet: ""
